/- AUTO-GENERATED by monotile/export_strag_trees.py from
   cube_strag34_done.jsonl — do not edit by hand.

   The 34 straggler maximal-empty masks' cube-and-conquer trees
   (phase-bit splits, leaves round-trip checked against the checkpoint).
   Per-leaf UNSAT is the cake_lpr-trusted axiom; covers are kernel-proven
   (CubeCover.VTree.covers). UNIFIED EVIDENCE (2026-08-06, R6): all 387
   leaves re-exported from the current proven encoder (emptyCNFX bases
   via ExportEmptyCNF + cube units) and re-verified through the R2 color
   pipeline (cadical --lrat → cake_lpr, certs deleted after each check) —
   monotile/bumpdent_frontier_verified.txt, 387/387, 0 failures
   (gen_bumpdent_certs.py). -/
import LeanFlocq.CubeCover
import LeanFlocq.AnyK3DEmptyEnc

open AnyK3D Std.Sat

namespace AnyK3D

/-- The phase-bit split order for an nc-cell box (Lean 0-based vars:
bVar nc ci k = nc*24 + ci*5 + k). -/
def phaseOrder (nc : Nat) : List Nat :=
  (List.range nc).flatMap fun ci => (List.range 5).map fun k =>
    nc * 24 + ci * 5 + k

/-- straggler 268: mask 1133644657102597908333363, box 5^3 (1 leaves). -/
def stragMask0 : Nat := 1133644657102597908333363
def stragDim0 : Nat := 5
def stragShape0 : String :=
  "F"
def stragTree0 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 125) (stragShape0.data.map (· == 'T'))
/-- straggler 542: mask 1133644657102600324254771, box 5^3 (1 leaves). -/
def stragMask1 : Nat := 1133644657102600324254771
def stragDim1 : Nat := 5
def stragShape1 : String :=
  "F"
def stragTree1 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 125) (stragShape1.data.map (· == 'T'))
/-- straggler 1668: mask 17708928406942686905283, box 4^3 (1 leaves). -/
def stragMask2 : Nat := 17708928406942686905283
def stragDim2 : Nat := 4
def stragShape2 : String :=
  "F"
def stragTree2 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 64) (stragShape2.data.map (· == 'T'))
/-- straggler 1915: mask 1133644657102600324252611, box 4^3 (1 leaves). -/
def stragMask3 : Nat := 1133644657102600324252611
def stragDim3 : Nat := 4
def stragShape3 : String :=
  "F"
def stragTree3 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 64) (stragShape3.data.map (· == 'T'))
/-- straggler 1987: mask 1137795174519184973366211, box 4^3 (1 leaves). -/
def stragMask4 : Nat := 1137795174519184973366211
def stragDim4 : Nat := 4
def stragShape4 : String :=
  "F"
def stragTree4 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 64) (stragShape4.data.map (· == 'T'))
/-- straggler 6585: mask 2725471849302777286102019, box 6^3 (1 leaves). -/
def stragMask5 : Nat := 2725471849302777286102019
def stragDim5 : Nat := 6
def stragShape5 : String :=
  "F"
def stragTree5 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 216) (stragShape5.data.map (· == 'T'))
/-- straggler 6586: mask 3027408156305653273463811, box 4^3 (1 leaves). -/
def stragMask6 : Nat := 3027408156305653273463811
def stragDim6 : Nat := 4
def stragShape6 : String :=
  "F"
def stragTree6 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 64) (stragShape6.data.map (· == 'T'))
/-- straggler 6600: mask 1824034806651025920887811, box 4^3 (1 leaves). -/
def stragMask7 : Nat := 1824034806651025920887811
def stragDim7 : Nat := 4
def stragShape7 : String :=
  "F"
def stragTree7 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 64) (stragShape7.data.map (· == 'T'))
/-- straggler 6664: mask 2725250488373909951351811, box 4^3 (1 leaves). -/
def stragMask8 : Nat := 2725250488373909951351811
def stragDim8 : Nat := 4
def stragShape8 : String :=
  "F"
def stragTree8 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 64) (stragShape8.data.map (· == 'T'))
/-- straggler 6671: mask 1522983943367828340476931, box 4^3 (1 leaves). -/
def stragMask9 : Nat := 1522983943367828340476931
def stragDim9 : Nat := 4
def stragShape9 : String :=
  "F"
def stragTree9 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 64) (stragShape9.data.map (· == 'T'))
/-- straggler 6679: mask 1825233845015834221612035, box 6^3 (1 leaves). -/
def stragMask10 : Nat := 1825233845015834221612035
def stragDim10 : Nat := 6
def stragShape10 : String :=
  "F"
def stragTree10 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 216) (stragShape10.data.map (· == 'T'))
/-- straggler 9572: mask 3027408742864320634814467, box 4^3 (1 leaves). -/
def stragMask11 : Nat := 3027408742864320634814467
def stragDim11 : Nat := 4
def stragShape11 : String :=
  "F"
def stragTree11 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 64) (stragShape11.data.map (· == 'T'))
/-- straggler 9656: mask 1522984107714030635843587, box 4^3 (1 leaves). -/
def stragMask12 : Nat := 1522984107714030635843587
def stragDim12 : Nat := 4
def stragShape12 : String :=
  "F"
def stragTree12 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 64) (stragShape12.data.map (· == 'T'))
/-- straggler 16141: mask 1137796255331414955786243, box 4^3 (5 leaves). -/
def stragMask13 : Nat := 1137796255331414955786243
def stragDim13 : Nat := 4
def stragShape13 : String :=
  "TFTFTFTFF"
def stragTree13 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 64) (stragShape13.data.map (· == 'T'))
/-- straggler 16170: mask 1133645742136890532823043, box 6^3 (266 leaves). -/
def stragMask14 : Nat := 1133645742136890532823043
def stragDim14 : Nat := 6
def stragShape14 : String :=
  "TTTTTTTTTTTFFTFFFTFTTFFFTFFTTTFTTFFFTFFTFFTTTTTTTTFFFFFFTFTTFFFTFTTTTTFFFFTFFFTTFTFFTFFTTTTTFFTFFTTTTFFFFFTTFFFFTTTTTTFFFTTTTFFFFFTTTFFFTFFTTTTFTTTTFTFFFFFTTTFFFFTTTTTTFFFFFFFTTTTFFFFFTTTFTFTFTTTFFFFTTFTFTTTFTFFFFFFTTTTTTTFFFTFFTTFFFTFFTTTTTFFFTFFTTTFFFFFTTTTTTTFTTFFTFFFTFTFFTFFTTTFTTTTTTFFFFFFFTTFTTTFTTFFFFFFFTTTFTTFTFFFFTFFTTTTFFFTTTTFFFFFFTTTTTFFTTTFFTTTFFFFTFTFFTTTTTTTTFFFFFTFTFFTFTTTTTTFFFFTFFTTFFFFTTTFFTTFFFTFFFTTTTTFFFTFFTTTFTTFFFFTFFTTTTFTTTFFFFTFFTTFFFFTTTTTTTFFFFTFTFFTTTTFFFTFFTTFFFTTTTFFFTFTFFFTTTTTFFFFTTFFFTTFTFFF"
def stragTree14 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 216) (stragShape14.data.map (· == 'T'))
/-- straggler 16221: mask 1364763917771456143949827, box 5^3 (1 leaves). -/
def stragMask15 : Nat := 1364763917771456143949827
def stragDim15 : Nat := 5
def stragShape15 : String :=
  "F"
def stragTree15 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 125) (stragShape15.data.map (· == 'T'))
/-- straggler 16228: mask 2578412103868954963869699, box 5^3 (1 leaves). -/
def stragMask16 : Nat := 2578412103868954963869699
def stragDim16 : Nat := 5
def stragShape16 : String :=
  "F"
def stragTree16 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 125) (stragShape16.data.map (· == 'T'))
/-- straggler 16818: mask 227559049251804181168131, box 5^3 (1 leaves). -/
def stragMask17 : Nat := 227559049251804181168131
def stragDim17 : Nat := 5
def stragShape17 : String :=
  "F"
def stragTree17 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 125) (stragShape17.data.map (· == 'T'))
/-- straggler 24647: mask 2725472432488091438104849, box 5^3 (6 leaves). -/
def stragMask18 : Nat := 2725472432488091438104849
def stragDim18 : Nat := 5
def stragShape18 : String :=
  "TTFFTTFFTFF"
def stragTree18 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 125) (stragShape18.data.map (· == 'T'))
/-- straggler 24730: mask 1825233936177151004410129, box 5^3 (8 leaves). -/
def stragMask19 : Nat := 1825233936177151004410129
def stragDim19 : Nat := 5
def stragShape19 : String :=
  "TTTFFTFFTTFFTFF"
def stragTree19 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 125) (stragShape19.data.map (· == 'T'))
/-- straggler 28077: mask 3027408742864320643285537, box 5^3 (14 leaves). -/
def stragMask20 : Nat := 3027408742864320643285537
def stragDim20 : Nat := 5
def stragShape20 : String :=
  "TTTTFFFTTFFTFFTTTFFFTTFFTFF"
def stragTree20 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 125) (stragShape20.data.map (· == 'T'))
/-- straggler 28111: mask 2725250787828101072126497, box 5^3 (16 leaves). -/
def stragMask21 : Nat := 2725250787828101072126497
def stragDim21 : Nat := 5
def stragShape21 : String :=
  "TTTTFFTTFFFTTTFFFFTTTFFFTTFFTFF"
def stragTree21 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 125) (stragShape21.data.map (· == 'T'))
/-- straggler 29085: mask 4723451569042320588833, box 5^3 (1 leaves). -/
def stragMask22 : Nat := 4723451569042320588833
def stragDim22 : Nat := 5
def stragShape22 : String :=
  "F"
def stragTree22 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 125) (stragShape22.data.map (· == 'T'))
/-- straggler 29086: mask 9149589282822044057633, box 5^3 (1 leaves). -/
def stragMask23 : Nat := 9149589282822044057633
def stragDim23 : Nat := 5
def stragShape23 : String :=
  "F"
def stragTree23 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 125) (stragShape23.data.map (· == 'T'))
/-- straggler 29948: mask 1208925891390748252700705, box 5^3 (1 leaves). -/
def stragMask24 : Nat := 1208925891390748252700705
def stragDim24 : Nat := 5
def stragShape24 : String :=
  "F"
def stragTree24 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 125) (stragShape24.data.map (· == 'T'))
/-- straggler 30535: mask 3027038653928967019561281, box 4^3 (1 leaves). -/
def stragMask25 : Nat := 3027038653928967019561281
def stragDim25 : Nat := 4
def stragShape25 : String :=
  "F"
def stragTree25 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 64) (stragShape25.data.map (· == 'T'))
/-- straggler 30950: mask 2427317161954448092185153, box 4^3 (1 leaves). -/
def stragMask26 : Nat := 2427317161954448092185153
def stragDim26 : Nat := 4
def stragShape26 : String :=
  "F"
def stragTree26 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 64) (stragShape26.data.map (· == 'T'))
/-- straggler 40995: mask 1137795174502684732425217, box 4^3 (1 leaves). -/
def stragMask27 : Nat := 1137795174502684732425217
def stragDim27 : Nat := 4
def stragShape27 : String :=
  "F"
def stragTree27 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 64) (stragShape27.data.map (· == 'T'))
/-- straggler 43275: mask 1133644657101561965578241, box 4^3 (1 leaves). -/
def stragMask28 : Nat := 1133644657101561965578241
def stragDim28 : Nat := 4
def stragShape28 : String :=
  "F"
def stragTree28 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 64) (stragShape28.data.map (· == 'T'))
/-- straggler 48285: mask 4703923978448079421441, box 4^3 (1 leaves). -/
def stragMask29 : Nat := 4703923978448079421441
def stragDim29 : Nat := 4
def stragShape29 : String :=
  "F"
def stragTree29 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 64) (stragShape29.data.map (· == 'T'))
/-- straggler 48311: mask 1137795246259020905840641, box 5^3 (1 leaves). -/
def stragMask30 : Nat := 1137795246259020905840641
def stragDim30 : Nat := 5
def stragShape30 : String :=
  "F"
def stragTree30 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 125) (stragShape30.data.map (· == 'T'))
/-- straggler 56936: mask 1137796255346808388059120, box 4^3 (45 leaves). -/
def stragMask31 : Nat := 1137796255346808388059120
def stragDim31 : Nat := 4
def stragShape31 : String :=
  "TTTTTFFFTTFTFFTFFTTTFFFTTFFTFFTTTFTTTFFTFTFFFTTFFTTTFFFFTTTTFFTTTFFTFFFTFFTTTFFTFTFFTTFFF"
def stragTree31 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 64) (stragShape31.data.map (· == 'T'))
/-- straggler 56969: mask 1180659175742614015984, box 4^3 (1 leaves). -/
def stragMask32 : Nat := 1180659175742614015984
def stragDim32 : Nat := 4
def stragShape32 : String :=
  "F"
def stragTree32 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 64) (stragShape32.data.map (· == 'T'))
/-- straggler 56979: mask 148654832992919752688, box 4^3 (1 leaves). -/
def stragMask33 : Nat := 148654832992919752688
def stragDim33 : Nat := 4
def stragShape33 : String :=
  "F"
def stragTree33 : CubeCover.VTree :=
  CubeCover.parseTree (phaseOrder 64) (stragShape33.data.map (· == 'T'))

/-! ## the cake_lpr-trusted leaf facts (see stream_verify pattern;
verification in monotile/verify_strag_leaves.py) -/

axiom stragLeafUnsat0 :
    ∀ cube ∈ stragTree0.cubes,
      (emptyCNFX stragMask0 stragDim0 stragDim0 stragDim0 ++ cube).Unsat

/-- straggler 268 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat0 :
    (emptyCNFX stragMask0 stragDim0 stragDim0 stragDim0).Unsat :=
  stragTree0.unsat _ stragLeafUnsat0

/-- straggler 268 has no space tiling (emptyX_sound). -/
theorem stragEmpty0 : ¬ ∃ ω, IsTiling (relOfMask stragMask0) ω :=
  emptyX_sound (by norm_num [stragDim0] : 0 < stragDim0)
    (by norm_num [stragDim0]) stragUnsat0
axiom stragLeafUnsat1 :
    ∀ cube ∈ stragTree1.cubes,
      (emptyCNFX stragMask1 stragDim1 stragDim1 stragDim1 ++ cube).Unsat

/-- straggler 542 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat1 :
    (emptyCNFX stragMask1 stragDim1 stragDim1 stragDim1).Unsat :=
  stragTree1.unsat _ stragLeafUnsat1

/-- straggler 542 has no space tiling (emptyX_sound). -/
theorem stragEmpty1 : ¬ ∃ ω, IsTiling (relOfMask stragMask1) ω :=
  emptyX_sound (by norm_num [stragDim1] : 0 < stragDim1)
    (by norm_num [stragDim1]) stragUnsat1
axiom stragLeafUnsat2 :
    ∀ cube ∈ stragTree2.cubes,
      (emptyCNFX stragMask2 stragDim2 stragDim2 stragDim2 ++ cube).Unsat

/-- straggler 1668 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat2 :
    (emptyCNFX stragMask2 stragDim2 stragDim2 stragDim2).Unsat :=
  stragTree2.unsat _ stragLeafUnsat2

/-- straggler 1668 has no space tiling (emptyX_sound). -/
theorem stragEmpty2 : ¬ ∃ ω, IsTiling (relOfMask stragMask2) ω :=
  emptyX_sound (by norm_num [stragDim2] : 0 < stragDim2)
    (by norm_num [stragDim2]) stragUnsat2
axiom stragLeafUnsat3 :
    ∀ cube ∈ stragTree3.cubes,
      (emptyCNFX stragMask3 stragDim3 stragDim3 stragDim3 ++ cube).Unsat

/-- straggler 1915 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat3 :
    (emptyCNFX stragMask3 stragDim3 stragDim3 stragDim3).Unsat :=
  stragTree3.unsat _ stragLeafUnsat3

/-- straggler 1915 has no space tiling (emptyX_sound). -/
theorem stragEmpty3 : ¬ ∃ ω, IsTiling (relOfMask stragMask3) ω :=
  emptyX_sound (by norm_num [stragDim3] : 0 < stragDim3)
    (by norm_num [stragDim3]) stragUnsat3
axiom stragLeafUnsat4 :
    ∀ cube ∈ stragTree4.cubes,
      (emptyCNFX stragMask4 stragDim4 stragDim4 stragDim4 ++ cube).Unsat

/-- straggler 1987 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat4 :
    (emptyCNFX stragMask4 stragDim4 stragDim4 stragDim4).Unsat :=
  stragTree4.unsat _ stragLeafUnsat4

/-- straggler 1987 has no space tiling (emptyX_sound). -/
theorem stragEmpty4 : ¬ ∃ ω, IsTiling (relOfMask stragMask4) ω :=
  emptyX_sound (by norm_num [stragDim4] : 0 < stragDim4)
    (by norm_num [stragDim4]) stragUnsat4
axiom stragLeafUnsat5 :
    ∀ cube ∈ stragTree5.cubes,
      (emptyCNFX stragMask5 stragDim5 stragDim5 stragDim5 ++ cube).Unsat

/-- straggler 6585 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat5 :
    (emptyCNFX stragMask5 stragDim5 stragDim5 stragDim5).Unsat :=
  stragTree5.unsat _ stragLeafUnsat5

/-- straggler 6585 has no space tiling (emptyX_sound). -/
theorem stragEmpty5 : ¬ ∃ ω, IsTiling (relOfMask stragMask5) ω :=
  emptyX_sound (by norm_num [stragDim5] : 0 < stragDim5)
    (by norm_num [stragDim5]) stragUnsat5
axiom stragLeafUnsat6 :
    ∀ cube ∈ stragTree6.cubes,
      (emptyCNFX stragMask6 stragDim6 stragDim6 stragDim6 ++ cube).Unsat

/-- straggler 6586 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat6 :
    (emptyCNFX stragMask6 stragDim6 stragDim6 stragDim6).Unsat :=
  stragTree6.unsat _ stragLeafUnsat6

/-- straggler 6586 has no space tiling (emptyX_sound). -/
theorem stragEmpty6 : ¬ ∃ ω, IsTiling (relOfMask stragMask6) ω :=
  emptyX_sound (by norm_num [stragDim6] : 0 < stragDim6)
    (by norm_num [stragDim6]) stragUnsat6
axiom stragLeafUnsat7 :
    ∀ cube ∈ stragTree7.cubes,
      (emptyCNFX stragMask7 stragDim7 stragDim7 stragDim7 ++ cube).Unsat

/-- straggler 6600 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat7 :
    (emptyCNFX stragMask7 stragDim7 stragDim7 stragDim7).Unsat :=
  stragTree7.unsat _ stragLeafUnsat7

/-- straggler 6600 has no space tiling (emptyX_sound). -/
theorem stragEmpty7 : ¬ ∃ ω, IsTiling (relOfMask stragMask7) ω :=
  emptyX_sound (by norm_num [stragDim7] : 0 < stragDim7)
    (by norm_num [stragDim7]) stragUnsat7
axiom stragLeafUnsat8 :
    ∀ cube ∈ stragTree8.cubes,
      (emptyCNFX stragMask8 stragDim8 stragDim8 stragDim8 ++ cube).Unsat

/-- straggler 6664 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat8 :
    (emptyCNFX stragMask8 stragDim8 stragDim8 stragDim8).Unsat :=
  stragTree8.unsat _ stragLeafUnsat8

/-- straggler 6664 has no space tiling (emptyX_sound). -/
theorem stragEmpty8 : ¬ ∃ ω, IsTiling (relOfMask stragMask8) ω :=
  emptyX_sound (by norm_num [stragDim8] : 0 < stragDim8)
    (by norm_num [stragDim8]) stragUnsat8
axiom stragLeafUnsat9 :
    ∀ cube ∈ stragTree9.cubes,
      (emptyCNFX stragMask9 stragDim9 stragDim9 stragDim9 ++ cube).Unsat

/-- straggler 6671 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat9 :
    (emptyCNFX stragMask9 stragDim9 stragDim9 stragDim9).Unsat :=
  stragTree9.unsat _ stragLeafUnsat9

/-- straggler 6671 has no space tiling (emptyX_sound). -/
theorem stragEmpty9 : ¬ ∃ ω, IsTiling (relOfMask stragMask9) ω :=
  emptyX_sound (by norm_num [stragDim9] : 0 < stragDim9)
    (by norm_num [stragDim9]) stragUnsat9
axiom stragLeafUnsat10 :
    ∀ cube ∈ stragTree10.cubes,
      (emptyCNFX stragMask10 stragDim10 stragDim10 stragDim10 ++ cube).Unsat

/-- straggler 6679 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat10 :
    (emptyCNFX stragMask10 stragDim10 stragDim10 stragDim10).Unsat :=
  stragTree10.unsat _ stragLeafUnsat10

/-- straggler 6679 has no space tiling (emptyX_sound). -/
theorem stragEmpty10 : ¬ ∃ ω, IsTiling (relOfMask stragMask10) ω :=
  emptyX_sound (by norm_num [stragDim10] : 0 < stragDim10)
    (by norm_num [stragDim10]) stragUnsat10
axiom stragLeafUnsat11 :
    ∀ cube ∈ stragTree11.cubes,
      (emptyCNFX stragMask11 stragDim11 stragDim11 stragDim11 ++ cube).Unsat

/-- straggler 9572 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat11 :
    (emptyCNFX stragMask11 stragDim11 stragDim11 stragDim11).Unsat :=
  stragTree11.unsat _ stragLeafUnsat11

/-- straggler 9572 has no space tiling (emptyX_sound). -/
theorem stragEmpty11 : ¬ ∃ ω, IsTiling (relOfMask stragMask11) ω :=
  emptyX_sound (by norm_num [stragDim11] : 0 < stragDim11)
    (by norm_num [stragDim11]) stragUnsat11
axiom stragLeafUnsat12 :
    ∀ cube ∈ stragTree12.cubes,
      (emptyCNFX stragMask12 stragDim12 stragDim12 stragDim12 ++ cube).Unsat

/-- straggler 9656 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat12 :
    (emptyCNFX stragMask12 stragDim12 stragDim12 stragDim12).Unsat :=
  stragTree12.unsat _ stragLeafUnsat12

/-- straggler 9656 has no space tiling (emptyX_sound). -/
theorem stragEmpty12 : ¬ ∃ ω, IsTiling (relOfMask stragMask12) ω :=
  emptyX_sound (by norm_num [stragDim12] : 0 < stragDim12)
    (by norm_num [stragDim12]) stragUnsat12
axiom stragLeafUnsat13 :
    ∀ cube ∈ stragTree13.cubes,
      (emptyCNFX stragMask13 stragDim13 stragDim13 stragDim13 ++ cube).Unsat

/-- straggler 16141 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat13 :
    (emptyCNFX stragMask13 stragDim13 stragDim13 stragDim13).Unsat :=
  stragTree13.unsat _ stragLeafUnsat13

/-- straggler 16141 has no space tiling (emptyX_sound). -/
theorem stragEmpty13 : ¬ ∃ ω, IsTiling (relOfMask stragMask13) ω :=
  emptyX_sound (by norm_num [stragDim13] : 0 < stragDim13)
    (by norm_num [stragDim13]) stragUnsat13
axiom stragLeafUnsat14 :
    ∀ cube ∈ stragTree14.cubes,
      (emptyCNFX stragMask14 stragDim14 stragDim14 stragDim14 ++ cube).Unsat

/-- straggler 16170 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat14 :
    (emptyCNFX stragMask14 stragDim14 stragDim14 stragDim14).Unsat :=
  stragTree14.unsat _ stragLeafUnsat14

/-- straggler 16170 has no space tiling (emptyX_sound). -/
theorem stragEmpty14 : ¬ ∃ ω, IsTiling (relOfMask stragMask14) ω :=
  emptyX_sound (by norm_num [stragDim14] : 0 < stragDim14)
    (by norm_num [stragDim14]) stragUnsat14
axiom stragLeafUnsat15 :
    ∀ cube ∈ stragTree15.cubes,
      (emptyCNFX stragMask15 stragDim15 stragDim15 stragDim15 ++ cube).Unsat

/-- straggler 16221 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat15 :
    (emptyCNFX stragMask15 stragDim15 stragDim15 stragDim15).Unsat :=
  stragTree15.unsat _ stragLeafUnsat15

/-- straggler 16221 has no space tiling (emptyX_sound). -/
theorem stragEmpty15 : ¬ ∃ ω, IsTiling (relOfMask stragMask15) ω :=
  emptyX_sound (by norm_num [stragDim15] : 0 < stragDim15)
    (by norm_num [stragDim15]) stragUnsat15
axiom stragLeafUnsat16 :
    ∀ cube ∈ stragTree16.cubes,
      (emptyCNFX stragMask16 stragDim16 stragDim16 stragDim16 ++ cube).Unsat

/-- straggler 16228 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat16 :
    (emptyCNFX stragMask16 stragDim16 stragDim16 stragDim16).Unsat :=
  stragTree16.unsat _ stragLeafUnsat16

/-- straggler 16228 has no space tiling (emptyX_sound). -/
theorem stragEmpty16 : ¬ ∃ ω, IsTiling (relOfMask stragMask16) ω :=
  emptyX_sound (by norm_num [stragDim16] : 0 < stragDim16)
    (by norm_num [stragDim16]) stragUnsat16
axiom stragLeafUnsat17 :
    ∀ cube ∈ stragTree17.cubes,
      (emptyCNFX stragMask17 stragDim17 stragDim17 stragDim17 ++ cube).Unsat

/-- straggler 16818 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat17 :
    (emptyCNFX stragMask17 stragDim17 stragDim17 stragDim17).Unsat :=
  stragTree17.unsat _ stragLeafUnsat17

/-- straggler 16818 has no space tiling (emptyX_sound). -/
theorem stragEmpty17 : ¬ ∃ ω, IsTiling (relOfMask stragMask17) ω :=
  emptyX_sound (by norm_num [stragDim17] : 0 < stragDim17)
    (by norm_num [stragDim17]) stragUnsat17
axiom stragLeafUnsat18 :
    ∀ cube ∈ stragTree18.cubes,
      (emptyCNFX stragMask18 stragDim18 stragDim18 stragDim18 ++ cube).Unsat

/-- straggler 24647 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat18 :
    (emptyCNFX stragMask18 stragDim18 stragDim18 stragDim18).Unsat :=
  stragTree18.unsat _ stragLeafUnsat18

/-- straggler 24647 has no space tiling (emptyX_sound). -/
theorem stragEmpty18 : ¬ ∃ ω, IsTiling (relOfMask stragMask18) ω :=
  emptyX_sound (by norm_num [stragDim18] : 0 < stragDim18)
    (by norm_num [stragDim18]) stragUnsat18
axiom stragLeafUnsat19 :
    ∀ cube ∈ stragTree19.cubes,
      (emptyCNFX stragMask19 stragDim19 stragDim19 stragDim19 ++ cube).Unsat

/-- straggler 24730 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat19 :
    (emptyCNFX stragMask19 stragDim19 stragDim19 stragDim19).Unsat :=
  stragTree19.unsat _ stragLeafUnsat19

/-- straggler 24730 has no space tiling (emptyX_sound). -/
theorem stragEmpty19 : ¬ ∃ ω, IsTiling (relOfMask stragMask19) ω :=
  emptyX_sound (by norm_num [stragDim19] : 0 < stragDim19)
    (by norm_num [stragDim19]) stragUnsat19
axiom stragLeafUnsat20 :
    ∀ cube ∈ stragTree20.cubes,
      (emptyCNFX stragMask20 stragDim20 stragDim20 stragDim20 ++ cube).Unsat

/-- straggler 28077 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat20 :
    (emptyCNFX stragMask20 stragDim20 stragDim20 stragDim20).Unsat :=
  stragTree20.unsat _ stragLeafUnsat20

/-- straggler 28077 has no space tiling (emptyX_sound). -/
theorem stragEmpty20 : ¬ ∃ ω, IsTiling (relOfMask stragMask20) ω :=
  emptyX_sound (by norm_num [stragDim20] : 0 < stragDim20)
    (by norm_num [stragDim20]) stragUnsat20
axiom stragLeafUnsat21 :
    ∀ cube ∈ stragTree21.cubes,
      (emptyCNFX stragMask21 stragDim21 stragDim21 stragDim21 ++ cube).Unsat

/-- straggler 28111 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat21 :
    (emptyCNFX stragMask21 stragDim21 stragDim21 stragDim21).Unsat :=
  stragTree21.unsat _ stragLeafUnsat21

/-- straggler 28111 has no space tiling (emptyX_sound). -/
theorem stragEmpty21 : ¬ ∃ ω, IsTiling (relOfMask stragMask21) ω :=
  emptyX_sound (by norm_num [stragDim21] : 0 < stragDim21)
    (by norm_num [stragDim21]) stragUnsat21
axiom stragLeafUnsat22 :
    ∀ cube ∈ stragTree22.cubes,
      (emptyCNFX stragMask22 stragDim22 stragDim22 stragDim22 ++ cube).Unsat

/-- straggler 29085 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat22 :
    (emptyCNFX stragMask22 stragDim22 stragDim22 stragDim22).Unsat :=
  stragTree22.unsat _ stragLeafUnsat22

/-- straggler 29085 has no space tiling (emptyX_sound). -/
theorem stragEmpty22 : ¬ ∃ ω, IsTiling (relOfMask stragMask22) ω :=
  emptyX_sound (by norm_num [stragDim22] : 0 < stragDim22)
    (by norm_num [stragDim22]) stragUnsat22
axiom stragLeafUnsat23 :
    ∀ cube ∈ stragTree23.cubes,
      (emptyCNFX stragMask23 stragDim23 stragDim23 stragDim23 ++ cube).Unsat

/-- straggler 29086 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat23 :
    (emptyCNFX stragMask23 stragDim23 stragDim23 stragDim23).Unsat :=
  stragTree23.unsat _ stragLeafUnsat23

/-- straggler 29086 has no space tiling (emptyX_sound). -/
theorem stragEmpty23 : ¬ ∃ ω, IsTiling (relOfMask stragMask23) ω :=
  emptyX_sound (by norm_num [stragDim23] : 0 < stragDim23)
    (by norm_num [stragDim23]) stragUnsat23
axiom stragLeafUnsat24 :
    ∀ cube ∈ stragTree24.cubes,
      (emptyCNFX stragMask24 stragDim24 stragDim24 stragDim24 ++ cube).Unsat

/-- straggler 29948 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat24 :
    (emptyCNFX stragMask24 stragDim24 stragDim24 stragDim24).Unsat :=
  stragTree24.unsat _ stragLeafUnsat24

/-- straggler 29948 has no space tiling (emptyX_sound). -/
theorem stragEmpty24 : ¬ ∃ ω, IsTiling (relOfMask stragMask24) ω :=
  emptyX_sound (by norm_num [stragDim24] : 0 < stragDim24)
    (by norm_num [stragDim24]) stragUnsat24
axiom stragLeafUnsat25 :
    ∀ cube ∈ stragTree25.cubes,
      (emptyCNFX stragMask25 stragDim25 stragDim25 stragDim25 ++ cube).Unsat

/-- straggler 30535 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat25 :
    (emptyCNFX stragMask25 stragDim25 stragDim25 stragDim25).Unsat :=
  stragTree25.unsat _ stragLeafUnsat25

/-- straggler 30535 has no space tiling (emptyX_sound). -/
theorem stragEmpty25 : ¬ ∃ ω, IsTiling (relOfMask stragMask25) ω :=
  emptyX_sound (by norm_num [stragDim25] : 0 < stragDim25)
    (by norm_num [stragDim25]) stragUnsat25
axiom stragLeafUnsat26 :
    ∀ cube ∈ stragTree26.cubes,
      (emptyCNFX stragMask26 stragDim26 stragDim26 stragDim26 ++ cube).Unsat

/-- straggler 30950 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat26 :
    (emptyCNFX stragMask26 stragDim26 stragDim26 stragDim26).Unsat :=
  stragTree26.unsat _ stragLeafUnsat26

/-- straggler 30950 has no space tiling (emptyX_sound). -/
theorem stragEmpty26 : ¬ ∃ ω, IsTiling (relOfMask stragMask26) ω :=
  emptyX_sound (by norm_num [stragDim26] : 0 < stragDim26)
    (by norm_num [stragDim26]) stragUnsat26
axiom stragLeafUnsat27 :
    ∀ cube ∈ stragTree27.cubes,
      (emptyCNFX stragMask27 stragDim27 stragDim27 stragDim27 ++ cube).Unsat

/-- straggler 40995 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat27 :
    (emptyCNFX stragMask27 stragDim27 stragDim27 stragDim27).Unsat :=
  stragTree27.unsat _ stragLeafUnsat27

/-- straggler 40995 has no space tiling (emptyX_sound). -/
theorem stragEmpty27 : ¬ ∃ ω, IsTiling (relOfMask stragMask27) ω :=
  emptyX_sound (by norm_num [stragDim27] : 0 < stragDim27)
    (by norm_num [stragDim27]) stragUnsat27
axiom stragLeafUnsat28 :
    ∀ cube ∈ stragTree28.cubes,
      (emptyCNFX stragMask28 stragDim28 stragDim28 stragDim28 ++ cube).Unsat

/-- straggler 43275 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat28 :
    (emptyCNFX stragMask28 stragDim28 stragDim28 stragDim28).Unsat :=
  stragTree28.unsat _ stragLeafUnsat28

/-- straggler 43275 has no space tiling (emptyX_sound). -/
theorem stragEmpty28 : ¬ ∃ ω, IsTiling (relOfMask stragMask28) ω :=
  emptyX_sound (by norm_num [stragDim28] : 0 < stragDim28)
    (by norm_num [stragDim28]) stragUnsat28
axiom stragLeafUnsat29 :
    ∀ cube ∈ stragTree29.cubes,
      (emptyCNFX stragMask29 stragDim29 stragDim29 stragDim29 ++ cube).Unsat

/-- straggler 48285 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat29 :
    (emptyCNFX stragMask29 stragDim29 stragDim29 stragDim29).Unsat :=
  stragTree29.unsat _ stragLeafUnsat29

/-- straggler 48285 has no space tiling (emptyX_sound). -/
theorem stragEmpty29 : ¬ ∃ ω, IsTiling (relOfMask stragMask29) ω :=
  emptyX_sound (by norm_num [stragDim29] : 0 < stragDim29)
    (by norm_num [stragDim29]) stragUnsat29
axiom stragLeafUnsat30 :
    ∀ cube ∈ stragTree30.cubes,
      (emptyCNFX stragMask30 stragDim30 stragDim30 stragDim30 ++ cube).Unsat

/-- straggler 48311 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat30 :
    (emptyCNFX stragMask30 stragDim30 stragDim30 stragDim30).Unsat :=
  stragTree30.unsat _ stragLeafUnsat30

/-- straggler 48311 has no space tiling (emptyX_sound). -/
theorem stragEmpty30 : ¬ ∃ ω, IsTiling (relOfMask stragMask30) ω :=
  emptyX_sound (by norm_num [stragDim30] : 0 < stragDim30)
    (by norm_num [stragDim30]) stragUnsat30
axiom stragLeafUnsat31 :
    ∀ cube ∈ stragTree31.cubes,
      (emptyCNFX stragMask31 stragDim31 stragDim31 stragDim31 ++ cube).Unsat

/-- straggler 56936 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat31 :
    (emptyCNFX stragMask31 stragDim31 stragDim31 stragDim31).Unsat :=
  stragTree31.unsat _ stragLeafUnsat31

/-- straggler 56936 has no space tiling (emptyX_sound). -/
theorem stragEmpty31 : ¬ ∃ ω, IsTiling (relOfMask stragMask31) ω :=
  emptyX_sound (by norm_num [stragDim31] : 0 < stragDim31)
    (by norm_num [stragDim31]) stragUnsat31
axiom stragLeafUnsat32 :
    ∀ cube ∈ stragTree32.cubes,
      (emptyCNFX stragMask32 stragDim32 stragDim32 stragDim32 ++ cube).Unsat

/-- straggler 56969 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat32 :
    (emptyCNFX stragMask32 stragDim32 stragDim32 stragDim32).Unsat :=
  stragTree32.unsat _ stragLeafUnsat32

/-- straggler 56969 has no space tiling (emptyX_sound). -/
theorem stragEmpty32 : ¬ ∃ ω, IsTiling (relOfMask stragMask32) ω :=
  emptyX_sound (by norm_num [stragDim32] : 0 < stragDim32)
    (by norm_num [stragDim32]) stragUnsat32
axiom stragLeafUnsat33 :
    ∀ cube ∈ stragTree33.cubes,
      (emptyCNFX stragMask33 stragDim33 stragDim33 stragDim33 ++ cube).Unsat

/-- straggler 56979 is empty: the phase-extended box CNF is UNSAT. -/
theorem stragUnsat33 :
    (emptyCNFX stragMask33 stragDim33 stragDim33 stragDim33).Unsat :=
  stragTree33.unsat _ stragLeafUnsat33

/-- straggler 56979 has no space tiling (emptyX_sound). -/
theorem stragEmpty33 : ¬ ∃ ω, IsTiling (relOfMask stragMask33) ω :=
  emptyX_sound (by norm_num [stragDim33] : 0 < stragDim33)
    (by norm_num [stragDim33]) stragUnsat33

end AnyK3D
