/-
# Color M4-coverage: verdict lookup + coverage decode for the color census

The color analogue of `AnyK3DCoverage.lean`, adapted to the color
track's data layout: instead of frontier domination, the 414,079
canonical profiles carry a UNIFIED VERDICT TABLE
(`AnyK3DColorVerdictData.lean`, autogenerated): each canonical profile
tagged by its verified tier — 0 periodic (torus witness), 1 density
(density-kill), 2 emptyF (frontier box-UNSAT, cake-backed), 3 emptyI
(maskLe inheritance).

The coverage check itself (the heavy `native_decide` over the 9,341,248
census masks) lives in `AnyK3DColorCoverageCheck.lean`, along with the
assembly-facing decode `mem_censusFastC_covered`. This file has:

* `sublistOf` — a greedy subsequence check with its membership
  soundness lemma (no sortedness needed: subsequence implies
  membership directly);
* `canonOf` — the canonical rotation of a mask (min over the 24
  `permMask`s), with `canonOf_mem` (the min is achieved by some
  rotation);
* the four tier subsequence checks (each tag class of the verdict table
  is a subsequence of the corresponding Lean-side tier data);
* `colorVerdict_of_mem` — the unified verdict: every profile in the
  table is either periodic (`PeriodicRel`) or empty (no ℤ³ tiling).
-/
import Mathlib
import LeanFlocq.AnyK3DColorPeriodicAll
import LeanFlocq.AnyK3DDensityKillsAll
import LeanFlocq.AnyK3DColorEmpty
import LeanFlocq.AnyK3DColorVerdictData
import LeanFlocq.AnyK3DTransport

set_option maxRecDepth 1000000
set_option maxHeartbeats 8000000

namespace AnyK3D

/-! ## sublistOf: greedy subsequence check -/

/-- Greedy subsequence check (correct for subsequences: matching the
earliest possible position is optimal). -/
def sublistOf : List ℕ → List ℕ → Bool
  | [], _ => true
  | _ :: _, [] => false
  | x :: xs, y :: ys =>
    if x == y then sublistOf xs ys else sublistOf (x :: xs) ys

/-- Subsequence membership soundness (no sortedness needed). -/
theorem mem_of_sublistOf {a b : List ℕ} (h : sublistOf a b = true) {x : ℕ}
    (hx : x ∈ a) : x ∈ b := by
  induction b generalizing a with
  | nil =>
    cases a with
    | nil => simp at hx
    | cons x' xs => simp [sublistOf] at h
  | cons y ys ih =>
    cases a with
    | nil => simp at hx
    | cons x' xs =>
      simp only [sublistOf] at h
      by_cases hxy : x' == y
      · simp only [hxy, if_true] at h
        rcases List.mem_cons.mp hx with rfl | hxs
        · exact List.mem_cons.mpr (Or.inl (beq_iff_eq.mp hxy))
        · exact List.mem_cons_of_mem y (ih h hxs)
      · simp only [hxy, if_false] at h
        exact List.mem_cons_of_mem y (ih h hx)

/-! ## canonOf: the canonical rotation of a mask -/

/-- The ascending bit list of a mask (the lexicographic key matching
Python's `sorted` equation lists). -/
def lexKey (m : ℕ) : List ℕ := (List.range 84).filter fun i => m.testBit i

/-- Lexicographic comparison of ascending bit lists (matching Python's
tuple ordering: shorter proper prefix is smaller). -/
def lexLt : List ℕ → List ℕ → Bool
  | [], [] => false
  | [], _ :: _ => true
  | _ :: _, [] => false
  | x :: xs, y :: ys =>
    if x < y then true else if x == y then lexLt xs ys else false

/-- The canonical form of a mask: the LEXICOGRAPHIC min over its 24
rotations' ascending bit lists (matching `color_orbits.py`'s `min` over
the sorted eqperm images — NOT the numeric min over masks; the orbit is
the same set in either `permMask` direction, so the `permMask`-based
computation agrees with the Python canonicalization, sampled 20k/20k in
`monotile/check_color_coverage_sample.py`). -/
def canonOf (m : ℕ) : ℕ :=
  (List.range 24).foldl
    (fun acc g =>
      let pg := permMask g m
      if lexLt (lexKey pg) (lexKey acc) then pg else acc)
    (permMask 0 m)

/-- The lex-min over the rotations is achieved by some rotation. -/
theorem canonOf_mem (m : ℕ) : ∃ g < 24, permMask g m = canonOf m := by
  unfold canonOf
  have gen : ∀ (l : List ℕ) (g₀ : ℕ) (acc : ℕ), permMask g₀ m = acc →
      ∃ g ∈ g₀ :: l, permMask g m =
        (l.foldl (fun a g =>
          let pg := permMask g m
          if lexLt (lexKey pg) (lexKey a) then pg else a) acc) := by
    intro l
    induction l with
    | nil => intro g₀ acc h; exact ⟨g₀, List.mem_cons_self, h⟩
    | cons g' gs ih =>
      intro g₀ acc h
      simp only [List.foldl_cons]
      have hstep : ∃ g'' ∈ [g₀, g'], permMask g'' m =
          (if lexLt (lexKey (permMask g' m)) (lexKey acc) = true
            then permMask g' m else acc) := by
        by_cases hc : lexLt (lexKey (permMask g' m)) (lexKey acc)
        · exact ⟨g', List.mem_cons_of_mem _ (List.mem_singleton_self _),
            by rw [if_pos hc]⟩
        · exact ⟨g₀, List.mem_cons_self, by rw [if_neg hc, h]⟩
      obtain ⟨g'', hg'', hgm''⟩ := hstep
      obtain ⟨g, hg, hgm⟩ := ih g'' _ hgm''
      refine ⟨g, ?_, hgm⟩
      rcases List.mem_cons.mp hg with rfl | hg'
      · rcases List.mem_cons.mp hg'' with rfl | hg''
        · exact List.mem_cons_self
        · have he := List.mem_singleton.mp hg''
          subst he
          exact List.mem_cons_of_mem _ List.mem_cons_self
      · exact List.mem_cons_of_mem _ (List.mem_cons_of_mem _ hg')
  obtain ⟨g, hg, hgm⟩ := gen (List.range 24) 0 (permMask 0 m) rfl
  rcases List.mem_cons.mp hg with rfl | hg'
  · exact ⟨0, by norm_num, hgm⟩
  · exact ⟨g, List.mem_range.mp hg', hgm⟩

/-! ## The tier sources (Lean-side, already verified) -/

def periodicDataAll : Array (ℕ × ℕ × ℕ × ℕ × ℕ × Array ℕ) :=
  periodicData0 ++ periodicData1 ++ periodicData2 ++ periodicData3 ++
    periodicData4

def killsDataAll : Array (ℕ × ℕ) :=
  killsData0 ++ killsData1 ++ killsData2 ++ killsData3 ++ killsData4 ++
    killsData5 ++ killsData6 ++ killsData7 ++ killsData8 ++ killsData9 ++
    killsData10 ++ killsData11

/-- The frontier masks, in job order. -/
def frontierMasks : List ℕ :=
  (List.range frontierSize).map fun i => (frontierJob i).1

/-- The inheritance profiles. -/
def inheritMasks : List ℕ := colorInheritance.toList.map (·.1)

/-! ## Verdict-table hygiene and the tier subsequence checks -/

theorem colorAllProfs_size : colorAllProfs.size = 414079 := by
  native_decide

theorem colorAllProfs_tags :
    colorAllProfs.all (fun e => decide (e.2 < 4)) = true := by
  native_decide

/-- Tag 0 (periodic): every periodic-tagged profile is a periodicData
entry's profile. -/
theorem colorVerdict_sub_periodic :
    sublistOf ((colorAllProfs.toList.filter (fun e => e.2 == 0)).map (·.1))
      ((periodicDataAll.toList.map (·.2.1)).mergeSort (· ≤ ·)) = true := by
  native_decide

/-- Tag 1 (density): every density-tagged profile is a killsData
entry's profile. -/
theorem colorVerdict_sub_density :
    sublistOf ((colorAllProfs.toList.filter (fun e => e.2 == 1)).map (·.1))
      ((killsDataAll.toList.map (·.2)).mergeSort (· ≤ ·)) = true := by
  native_decide

/-- Tag 2 (emptyF): every frontier-tagged profile is a frontier job's
mask. -/
theorem colorVerdict_sub_emptyF :
    sublistOf ((colorAllProfs.toList.filter (fun e => e.2 == 2)).map (·.1))
      (frontierMasks.mergeSort (· ≤ ·)) = true := by
  native_decide

/-- Tag 3 (emptyI): every inheritance-tagged profile is an inheritance
pair's profile. -/
theorem colorVerdict_sub_emptyI :
    sublistOf ((colorAllProfs.toList.filter (fun e => e.2 == 3)).map (·.1))
      (inheritMasks.mergeSort (· ≤ ·)) = true := by
  native_decide

/-! ## The unified verdict -/

/-- `relOfHeld` of a packed profile IS `relOfMask` (definitional). -/
theorem relOfHeld_heldOfNat (p : ℕ) : relOfHeld (heldOfNat p) = relOfMask p :=
  rfl

/-- Generic 5-way Array-append membership split (kept abstract so
`simp` never sees the concrete data arrays — rewriting in a context
containing the big literals whnf-evaluates the append chains and blows
up). -/
theorem mem_append5 {α : Type*} (a : α) (x1 x2 x3 x4 x5 : Array α)
    (h : a ∈ x1 ++ x2 ++ x3 ++ x4 ++ x5) :
    a ∈ x1 ∨ a ∈ x2 ∨ a ∈ x3 ∨ a ∈ x4 ∨ a ∈ x5 := by
  simp only [Array.mem_append, or_assoc] at h
  exact h

/-- A periodicData entry from the appended array yields its chunk's
periodicity. -/
theorem mem_periodicDataAll {x : ℕ × ℕ × ℕ × ℕ × ℕ × Array ℕ}
    (hx : x ∈ periodicDataAll) :
    PeriodicRelTiles (relOfHeld (heldOfNat x.2.1)) := by
  have hx2 : x ∈ periodicData0 ++ periodicData1 ++ periodicData2 ++
      periodicData3 ++ periodicData4 := hx
  rcases mem_append5 x _ _ _ _ _ hx2 with h | h | h | h | h
  · exact periodicData0_periodic x h
  · exact periodicData1_periodic x h
  · exact periodicData2_periodic x h
  · exact periodicData3_periodic x h
  · exact periodicData4_periodic x h

/-- Generic 12-way Array-append membership split (see `mem_append5`). -/
theorem mem_append12 {α : Type*} (a : α)
    (x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 : Array α)
    (h : a ∈ x1 ++ x2 ++ x3 ++ x4 ++ x5 ++ x6 ++ x7 ++ x8 ++ x9 ++ x10 ++
      x11 ++ x12) :
    a ∈ x1 ∨ a ∈ x2 ∨ a ∈ x3 ∨ a ∈ x4 ∨ a ∈ x5 ∨ a ∈ x6 ∨ a ∈ x7 ∨
      a ∈ x8 ∨ a ∈ x9 ∨ a ∈ x10 ∨ a ∈ x11 ∨ a ∈ x12 := by
  simp only [Array.mem_append, or_assoc] at h
  exact h

/-- A killsData entry from the appended array yields its chunk's
emptiness. -/
theorem mem_killsDataAll {x : ℕ × ℕ} (hx : x ∈ killsDataAll) :
    ¬ ∃ ω, IsTiling (relOfHeld (heldOfNat x.2)) ω := by
  have hx2 : x ∈ killsData0 ++ killsData1 ++ killsData2 ++ killsData3 ++
      killsData4 ++ killsData5 ++ killsData6 ++ killsData7 ++ killsData8 ++
      killsData9 ++ killsData10 ++ killsData11 := hx
  rcases mem_append12 x _ _ _ _ _ _ _ _ _ _ _ _ hx2 with
    h | h | h | h | h | h | h | h | h | h | h | h
  · exact killsData0_empty x h
  · exact killsData1_empty x h
  · exact killsData2_empty x h
  · exact killsData3_empty x h
  · exact killsData4_empty x h
  · exact killsData5_empty x h
  · exact killsData6_empty x h
  · exact killsData7_empty x h
  · exact killsData8_empty x h
  · exact killsData9_empty x h
  · exact killsData10_empty x h
  · exact killsData11_empty x h

/-- The unified verdict: every profile in the verdict table is either
periodic or empty. -/
theorem colorVerdict_of_mem {p : ℕ}
    (hp : p ∈ colorAllProfs.toList.map (·.1)) :
    PeriodicRel (relOfMask p) ∨ ¬ ∃ ω, IsTiling (relOfMask p) ω := by
  obtain ⟨e, he, rfl⟩ := List.mem_map.mp hp
  have htag : e.2 < 4 :=
    of_decide_eq_true (Array.all_eq_true_iff_forall_mem.mp
      colorAllProfs_tags e (Array.mem_def.mpr he))
  have hmemF : ∀ t : ℕ, e.2 = t →
      e.1 ∈ (colorAllProfs.toList.filter (fun e' => e'.2 == t)).map (·.1) := by
    intro t ht
    exact List.mem_map.mpr ⟨e, List.mem_filter.mpr
      ⟨he, by simp [ht]⟩, rfl⟩
  rcases (show e.2 = 0 ∨ e.2 = 1 ∨ e.2 = 2 ∨ e.2 = 3 from by omega)
    with h | h | h | h
  · -- periodic
    left
    have hm := mem_of_sublistOf colorVerdict_sub_periodic (hmemF 0 h)
    rw [List.mem_mergeSort] at hm
    obtain ⟨x, hx, hxp⟩ := List.mem_map.mp hm
    have hper := mem_periodicDataAll (Array.mem_def.mpr hx)
    rw [hxp] at hper
    exact hper
  · -- density
    right
    have hm := mem_of_sublistOf colorVerdict_sub_density (hmemF 1 h)
    rw [List.mem_mergeSort] at hm
    obtain ⟨x, hx, hxp⟩ := List.mem_map.mp hm
    have hemp := mem_killsDataAll (Array.mem_def.mpr hx)
    rw [hxp] at hemp
    exact hemp
  · -- emptyF
    right
    have hm := mem_of_sublistOf colorVerdict_sub_emptyF (hmemF 2 h)
    rw [List.mem_mergeSort] at hm
    simp only [frontierMasks, List.mem_map, List.mem_range] at hm
    obtain ⟨i, hi, hip⟩ := hm
    rw [← hip]
    exact colorFrontierEmpty i hi
  · -- emptyI
    right
    have hm := mem_of_sublistOf colorVerdict_sub_emptyI (hmemF 3 h)
    rw [List.mem_mergeSort] at hm
    simp only [inheritMasks, List.mem_map] at hm
    obtain ⟨x, hx, hxp⟩ := hm
    have hemp := colorEmpty_of_inheritance x (Array.mem_def.mpr hx)
    rw [hxp] at hemp
    exact hemp

end AnyK3D
