/-
Aggregate of the density-kill chunks: 176,197 canonical color profiles
(42.5% of the census) have their ℤ³ emptiness kernel-verified by the
density lemma — no SAT certificates involved.

Per chunk `j`: `killsData{j}_verified` (the batch `native_decide`) and
`killsData{j}_empty` (every witness's SFT is empty, via `killOk_sound`).
This module only adds the total count. Data autogenerated by
monotile/color_density_export.py.
-/

import LeanFlocq.AnyK3DDensityKills0
import LeanFlocq.AnyK3DDensityKills1
import LeanFlocq.AnyK3DDensityKills2
import LeanFlocq.AnyK3DDensityKills3
import LeanFlocq.AnyK3DDensityKills4
import LeanFlocq.AnyK3DDensityKills5
import LeanFlocq.AnyK3DDensityKills6
import LeanFlocq.AnyK3DDensityKills7
import LeanFlocq.AnyK3DDensityKills8
import LeanFlocq.AnyK3DDensityKills9
import LeanFlocq.AnyK3DDensityKills10
import LeanFlocq.AnyK3DDensityKills11

namespace AnyK3D

/-- Total number of density-verified empty canonical color profiles. -/
theorem kills_total :
    killsData0.size + killsData1.size + killsData2.size + killsData3.size + killsData4.size + killsData5.size + killsData6.size + killsData7.size + killsData8.size + killsData9.size + killsData10.size + killsData11.size = 176197 := by
  native_decide

end AnyK3D
