/-
Density-kill checker: turns `monotile/color_density_export.py`'s kill
list into kernel-checked emptiness certificates — no SAT involved.

`killOk` verifies a packed witness (84-bit profile, A/P type masks)
against the density lemma's side conditions for the *symmetrized* pair
relation `pairSymOf` (symmetric by construction, so no per-profile
symmetry check is needed — and the symmetrized condition is the sound
one for non-symmetric relations: an A-face pointing either way across
an adjacency must land its partner in `P`). `killOk_sound` discharges
a verified witness into emptiness of the orientation SFT via
`ColorDensity.not_tileable_of_deficit`.

The data chunks (`AnyK3DDensityKills{j}.lean`, autogenerated) carry the
witnesses and one `native_decide` batch theorem per chunk.
-/

import LeanFlocq.AnyK3DColorDensity

namespace AnyK3D

open ColorDensity

/-- The symmetric closure of the induced pair relation. -/
@[reducible]
def pairSymOf (held : Fin 84 → Bool) (g h : Fin 6) : Prop :=
  pairOf held g h ∨ pairOf held h g

theorem pairSymOf_symm (held : Fin 84 → Bool) :
    ∀ g h, pairSymOf held g h → pairSymOf held h g :=
  fun _ _ hgh => hgh.elim Or.inr Or.inl

/-- Any ℤ³ tiling restricts to a box tiling for the symmetrized relation
(compatibility upgrades via `Or.inl`). -/
def boxTilingOfSym (held : Fin 84 → Bool) {L : ℕ}
    (ω : ℤ × ℤ × ℤ → Fin 24) (hω : IsTiling (relOfHeld held) ω) :
    BoxTiling (Fin 6) L (pairSymOf held) where
  face c d := faceOf (ω (embed c)) d
  face_bij c := faceOf_bijective (ω (embed c))
  compat c ax h := Or.inl ((boxTilingOf held ω hω).compat c ax h)

/-- A profile whose symmetrized pair relation has a deficient face-type
class has an empty orientation SFT. -/
theorem not_isTiling_of_deficient_sym (held : Fin 84 → Bool)
    (A B : Finset (Fin 6))
    (hpair : ∀ g ∈ A, ∀ h, pairSymOf held g h → h ∈ B)
    (hAB : B.card < A.card) :
    ¬ ∃ ω, IsTiling (relOfHeld held) ω := by
  rintro ⟨ω, hω⟩
  have hd : 1 ≤ A.card - B.card := Nat.sub_pos_of_lt hAB
  have hb : 6 < (A.card - B.card) * 7 := by
    have h7 : 7 ≤ (A.card - B.card) * 7 := by
      calc 7 = 1 * 7 := rfl
        _ ≤ (A.card - B.card) * 7 := Nat.mul_le_mul_right 7 hd
    omega
  exact ColorDensity.not_tileable_of_deficit (pairSymOf_symm held)
    hpair hAB hb ⟨boxTilingOfSym held ω hω⟩

/-! ## The packed checker -/

/-- An 84-bit equation profile packed as a Nat. -/
def heldOfNat (prof : Nat) : Fin 84 → Bool := fun i => prof.testBit i.val

/-- A 6-bit face-type mask as a finset. -/
def maskToFinset (m : Nat) : Finset (Fin 6) :=
  Finset.univ.filter (fun g => m.testBit g.val)

/-- Packed kill checker: class `A` (low 6 bits of `maskAP`) pairs only
into `P` (next 6 bits) under the symmetrized relation, with `|P| < |A|`. -/
def killOk (prof : Nat) (maskAP : Nat) : Bool :=
  decide (∀ g ∈ maskToFinset (maskAP &&& 63), ∀ h,
    pairSymOf (heldOfNat prof) g h → h ∈ maskToFinset ((maskAP >>> 6) &&& 63)) &&
  decide ((maskToFinset ((maskAP >>> 6) &&& 63)).card <
    (maskToFinset (maskAP &&& 63)).card)

/-- A verified kill witness implies the profile's SFT on ℤ³ is empty. -/
theorem killOk_sound (prof maskAP : Nat) (h : killOk prof maskAP = true) :
    ¬ ∃ ω, IsTiling (relOfHeld (heldOfNat prof)) ω := by
  rw [killOk, Bool.and_eq_true, decide_eq_true_eq, decide_eq_true_eq] at h
  exact not_isTiling_of_deficient_sym _ _ _ h.1 h.2

end AnyK3D
