/-
Aggregate of the periodic-witness chunks: all 41,824 periodic canonical
color profiles have their `PeriodicRelTiles` kernel-verified — each has a
rectangular torus witness checked by `torusOK` and lifted by
`torusOK_sound`. Data autogenerated by monotile/color_periodic_export.py
from regenerated lattice-torus solves (self-checked against the same
condition `torusOK` verifies).
-/

import LeanFlocq.AnyK3DColorPeriodicData0
import LeanFlocq.AnyK3DColorPeriodicData1
import LeanFlocq.AnyK3DColorPeriodicData2
import LeanFlocq.AnyK3DColorPeriodicData3
import LeanFlocq.AnyK3DColorPeriodicData4

namespace AnyK3D

/-- Total number of verified periodic color profiles. -/
theorem periodic_total :
    periodicData0.size + periodicData1.size + periodicData2.size + periodicData3.size + periodicData4.size = 41824 := by
  native_decide

end AnyK3D
